# version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: auditsmart-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: auditsmart
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - auditsmart-network

  backend:
    build: ./backend
    container_name: auditsmart-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=auditsmart
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/reports:/app/reports
    networks:
      - auditsmart-network
  frontend:
    build: ./frontend
    container_name: auditsmart-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - auditsmart-network

volumes:
  mongodb_data:

networks:
  auditsmart-network:
    driver: bridge