# version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: auditsmart-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: auditsmart
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - auditsmart-network

  backend:
    build: ./backend
    container_name: auditsmart-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=auditsmart
      - PYTHONPATH=/app
      - PATH=/root/.foundry/bin:/root/.cargo/bin:/usr/local/bin:/usr/bin:/bin
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/reports:/app/reports
      - ./backend/extracted:/app/extracted
      # Mount để cache Foundry và dependencies
      - foundry_cache:/root/.foundry
      - cargo_cache:/root/.cargo
    networks:
      - auditsmart-network

  frontend:
    build: ./frontend
    container_name: auditsmart-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
    networks:
      - auditsmart-network

volumes:
  mongodb_data:
  foundry_cache:
  cargo_cache:

networks:
  auditsmart-network:
    driver: bridge